-- Acadify — local seed data.
--
-- Runs automatically after migrations on `npm run db:reset`. It exists so a
-- developer gets a usable local stack in one command rather than clicking
-- through sign-up and creating subjects by hand every time they reset.
--
-- Rules for anything added here:
--   * Local only. This file is never applied to a hosted project.
--   * No real personal data, ever — not a real email, not a real file.
--   * Idempotent where it can be, so a partial reset does not wedge.
--
-- The schema exists as of Sprint 13, so this file can now be written — but it
-- is deliberately still a no-op, because seeding requires `db:reset`, which
-- requires Docker, which is not installed on the machine this was built on. A
-- seed nobody can run is worse than an empty one: it rots silently and fails
-- the first time someone with Docker tries a reset.
--
-- What it should insert, once there is a way to prove it works: an auth user, a
-- profile, two subjects and a handful of topics mirroring
-- src/features/dashboard/sample-data.ts, so the dashboard renders something
-- real and that placeholder file can be deleted (Sprint 70).
